/****************************************************************************
 *
 *   Generated by tools/generate_bet_tables.py. Do not edit by hand.
 *
 ****************************************************************************/

#pragma once

#include <cstddef>
#include <cstdint>

namespace thrust_feedback_control
{
namespace bet
{

struct BetSection {
	float r_over_R;
	float radius_m;
	float chord_m;
	float theta_rad;
	uint16_t airfoil_index;
};

static constexpr std::size_t kNumBetSections = 75;
static constexpr std::size_t kNumBetAirfoils = 75;
static constexpr std::size_t kNumBetAlpha = 61;
static constexpr std::size_t kNumBetRe = 7;

extern const BetSection kBetSections[kNumBetSections];
extern const float kBetAlphaGridDeg[kNumBetAlpha];
extern const float kBetReGrid[kNumBetRe];
extern const float kBetClTable[kNumBetAirfoils * kNumBetAlpha * kNumBetRe];
extern const float kBetCdTable[kNumBetAirfoils * kNumBetAlpha * kNumBetRe];

} // namespace bet
} // namespace thrust_feedback_control
