/****************************************************************************
 *
 *   Generated by tools/generate_bet_tables.py. Do not edit by hand.
 *
 ****************************************************************************/

#pragma once

#include <cstddef>

namespace thrust_feedback_control
{
namespace bet
{

static constexpr std::size_t kNumBetLiftRpm = 61;
static constexpr std::size_t kNumBetLiftFreestream = 11;
static constexpr std::size_t kNumBetLiftAlpha = 7;

extern const float kBetLiftRpmGrid[kNumBetLiftRpm];
extern const float kBetLiftFreestreamGrid[kNumBetLiftFreestream];
extern const float kBetLiftAlphaGridDeg[kNumBetLiftAlpha];
extern const float kBetLiftLookupN[kNumBetLiftAlpha * kNumBetLiftFreestream * kNumBetLiftRpm];

} // namespace bet
} // namespace thrust_feedback_control
